name: swapi_dart
description: A new Flutter package project.
version: 0.0.1
author: Robert Černjanski

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  hive: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  hive_generator: ^1.0.1

flutter:
